name: Deploy Project

permissions:
  contents: read
  packages: write
  id-token: write

on:
  # push:
  #   tags:
  #     - 'v*.*.*'  # Trigger on version tags like v1.0.0
  workflow_dispatch:
    project_name:
        description: 'Project name'
        required: true
        default: 'go-url-shortner'
    inputs:
      version:
        description: 'Version to deploy (e.g., 1.0.0)'
        required: true
        default: 'latest'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set deployment version
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            VERSION=${{ github.event.inputs.version }}
          else
            VERSION=${GITHUB_REF_NAME#refs/tags/}
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/${{ github.event.inputs.project_name }}
          echo "Building image $IMAGE:$VERSION"
          docker build -t $IMAGE:latest -t $IMAGE:$VERSION .
          docker push $IMAGE:latest
          docker push $IMAGE:$VERSION

      - name: Deploy on VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.SERVER_PROJECT_BASE_PATH }}/${{ github.event.inputs.project_name }}
            docker compose pull
            docker compose up -d --remove-orphans
            docker system prune -f
